spring:
  application:
    name: distinctride
  main:
    banner-mode: 'off'
  profiles:
    active: development

---

spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/distinctride?zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: distinctride
    password: distinctride-pw
    hikari:
      maximum-pool-size: 2

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/distinctride?useSSL=false&serverTimezone=UTC
    user: flyway
    password: flyway-pw
    schemas: distinctride

